// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/Child.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    OneRootChild: typeof import('./src/components/OneRootChild.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TwoRootChild: typeof import('./src/components/TwoRootChild.vue')['default']
  }
}
